using System.Collections.Generic;
using UnityEngine;

[RequireComponent(typeof(MeshFilter), typeof(MeshRenderer), typeof(MeshCollider))]
public class TerrainChunk : MonoBehaviour
{
    [SerializeField] private Vector2Int _chunkCoord;
    public Vector2Int ChunkCoord
    {
        get
        {
            if (_chunkCoord == Vector2Int.zero && gameObject != null && gameObject.name.StartsWith("Chunk_"))
            {
                string[] parts = gameObject.name.Split('_');
                if (parts.Length >= 3 && int.TryParse(parts[1], out int px) && int.TryParse(parts[2], out int pz))
                {
                    _chunkCoord = new Vector2Int(px, pz);
                }
            }
            return _chunkCoord;
        }
        private set => _chunkCoord = value;
    }
    private LowPolyTerrainConfig config;
    private int activeSeed;
    private MeshFilter meshFilter;
    private MeshCollider meshCollider;
    private Mesh runtimeMesh;
    private float[,] foliageHeightMap;

    public bool TryGetFoliageHeightMap(LowPolyTerrainConfig requestedConfig, int seed, out float[,] heights)
    {
        heights = foliageHeightMap;
        return requestedConfig == config && seed == activeSeed && heights != null &&
            heights.GetLength(0) == requestedConfig.chunkSize + 1;
    }

    private void Awake()
    {
        // Ensure coordinate reading and initialization even if the chunk was pregenerated by the Editor.
        _ = ChunkCoord;
    }

    public void Initialize(Vector2Int coord, LowPolyTerrainConfig configuration, int seedOverride = 0, bool autoGenerateMesh = true)
    {
        ChunkCoord = coord;
        config = configuration;
        foliageHeightMap = null;
        activeSeed = seedOverride != 0 ? seedOverride : (config != null ? config.seed : 4242);
        meshFilter = GetComponent<MeshFilter>();
        meshCollider = GetComponent<MeshCollider>();

        if (autoGenerateMesh)
        {
            GenerateMesh();
        }
    }

    public void GenerateMesh()
    {
        Mesh mesh = BuildMesh();
        ApplyMesh(mesh);
    }

    public void ApplyMesh(Mesh mesh)
    {
        if (meshFilter == null) meshFilter = GetComponent<MeshFilter>();
        if (meshCollider == null) meshCollider = GetComponent<MeshCollider>();

        meshFilter.sharedMesh = mesh;
        meshCollider.sharedMesh = mesh;

        // Both generation paths pass BuildMesh output here. Own only runtime
        // assignments; leave meshes authored in scenes or generated in edit mode.
        if (Application.isPlaying && runtimeMesh != mesh)
        {
            if (runtimeMesh != null) Destroy(runtimeMesh);
            runtimeMesh = mesh;
        }
    }

    private void OnDestroy()
    {
        if (runtimeMesh != null) Destroy(runtimeMesh);
    }

    public Mesh BuildMesh()
    {
        int size = config.chunkSize;
        float cellSize = config.cellSize;

        float halfMapX = (config.chunksX * size * cellSize) * 0.5f;
        float halfMapZ = (config.chunksZ * size * cellSize) * 0.5f;

        // 1. Height matrix with (size + 1) for seamless joins.
        float[,] heightMap = new float[size + 1, size + 1];

        for (int z = 0; z <= size; z++)
        {
            for (int x = 0; x <= size; x++)
            {
                // Global world coordinates.
                float worldX = (ChunkCoord.x * size + x) * cellSize;
                float worldZ = (ChunkCoord.y * size + z) * cellSize;

                heightMap[x, z] = TerrainNoise.SampleHeight(worldX, worldZ, config, activeSeed, halfMapX, halfMapZ);
            }
        }

        // Keep the existing samples for vegetation rather than evaluating terrain noise a second time.
        foliageHeightMap = heightMap;

        // 2. Mesh Construction with Duplicated Vertices (Flat Shading).
        List<Vector3> vertices = new List<Vector3>();
        List<int> triangles = new List<int>();
        List<Color> colors = new List<Color>();

        for (int z = 0; z < size; z++)
        {
            for (int x = 0; x < size; x++)
            {
                Vector3 p00 = new Vector3(x * cellSize, heightMap[x, z], z * cellSize);
                Vector3 p10 = new Vector3((x + 1) * cellSize, heightMap[x + 1, z], z * cellSize);
                Vector3 p01 = new Vector3(x * cellSize, heightMap[x, z + 1], (z + 1) * cellSize);
                Vector3 p11 = new Vector3((x + 1) * cellSize, heightMap[x + 1, z + 1], (z + 1) * cellSize);

                // Triangle 1 (p00, p01, p10).
                AddFace(p00, p01, p10, vertices, triangles, colors);
                // Triangle 2 (p10, p01, p11).
                AddFace(p10, p01, p11, vertices, triangles, colors);
            }
        }

        Mesh mesh = new Mesh();
        mesh.name = $"TerrainMesh_{ChunkCoord.x}_{ChunkCoord.y}";
        mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
        mesh.SetVertices(vertices);
        mesh.SetTriangles(triangles, 0);
        mesh.SetColors(colors);
        mesh.RecalculateNormals();
        mesh.RecalculateBounds();

        return mesh;
    }

    private void AddFace(Vector3 a, Vector3 b, Vector3 c, List<Vector3> verts, List<int> tris, List<Color> cols)
    {
        int startIndex = verts.Count;
        verts.Add(a);
        verts.Add(b);
        verts.Add(c);

        tris.Add(startIndex);
        tris.Add(startIndex + 1);
        tris.Add(startIndex + 2);

        // Calculate the flat face normal to check slope and lighting.
        Vector3 faceNormal = Vector3.Cross(b - a, c - a).normalized;
        float slopeAngle = Vector3.Angle(faceNormal, Vector3.up);

        float avgHeight = (a.y + b.y + c.y) / 3f;
        Color faceColor = EvaluateBiomeColor(avgHeight, slopeAngle, faceNormal);

        cols.Add(faceColor);
        cols.Add(faceColor);
        cols.Add(faceColor);
    }

    private Color EvaluateBiomeColor(float height, float slopeAngle, Vector3 faceNormal)
    {
        Color finalColor;

        // 1. Underwater (seabed with wet sand and deep rock).
        if (height <= config.waterLevel)
        {
            float depth = Mathf.Clamp01((config.waterLevel - height) / 3.0f);
            Color wetSand = config.sandColor * 0.72f;
            Color deepSeabed = config.rockColor * 0.52f;
            finalColor = Color.Lerp(wetSand, deepSeabed, depth);
        }
        // 2. Beach / Sand Transition.
        else if (height <= config.waterLevel + 1.0f)
        {
            float sandBlend = Mathf.Clamp01((height - config.waterLevel) / 1.0f);
            finalColor = Color.Lerp(config.sandColor, config.grassColor, sandBlend);
        }
        // 3. Steep Walls / Cliffs.
        else if (slopeAngle >= config.steepSlopeThreshold)
        {
            float steepness = Mathf.Clamp01((slopeAngle - config.steepSlopeThreshold) / 25f);
            finalColor = Color.Lerp(config.rockColor, config.cliffColor, steepness);
        }
        // 4. Snow on the Highest Peaks.
        else if (height >= config.heightMultiplier * 0.85f)
        {
            float snowBlend = Mathf.Clamp01((height - config.heightMultiplier * 0.85f) / (config.heightMultiplier * 0.15f));
            finalColor = Color.Lerp(config.rockColor, config.snowColor, snowBlend);
        }
        // 5. Mid-Elevation Mountain Rock.
        else if (height >= config.heightMultiplier * 0.62f)
        {
            float rockBlend = Mathf.Clamp01((height - config.heightMultiplier * 0.62f) / (config.heightMultiplier * 0.23f));
            finalColor = Color.Lerp(config.grassColor, config.rockColor, rockBlend);
        }
        // 6. Plains and Valley Vegetation.
        else
        {
            // Organic variation between sunlit grass and deep valley grass.
            float valleyBlend = Mathf.Clamp01(height / (config.heightMultiplier * 0.45f));
            finalColor = Color.Lerp(config.deepGrassColor, config.grassColor, valleyBlend);
        }

        // Apply crevice / facet occlusion (Facet Crease AO).
        if (config.facetAOIntensity > 0f && height > config.waterLevel)
        {
            float ao = 1f - (Mathf.Clamp01(slopeAngle / 90f) * config.facetAOIntensity);
            finalColor.r *= ao;
            finalColor.g *= ao;
            finalColor.b *= ao;
        }

        return finalColor;
    }
}
